### ISSUE TITLE
Add support for full length circRNA sequence detection

### ISSUE THREAD

**Issue by nictru** [nf-core/circrna#111]
### Description of feature

Currently, only the BSJs are detected and quantified, without knowing the exact sequences. There are several tools which can obtain the full length circRNA sequence from paired-end data listed below. Unfortunately, none of these tools can process single-end data.

We should then create a parameter for switching between BSJ level and Isoform level discovery.

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/circrna/issues/133
- [ ] https://github.com/nf-core/circrna/issues/134
- [ ] https://github.com/nf-core/circrna/issues/135
- [ ] https://github.com/nf-core/circrna/issues/136
```

**Comment by nictru** [comment]
Done via #211
