### ISSUE TITLE
Add strandedness column to samplesheet

### ISSUE THREAD

**Issue by nictru** [nf-core/circrna#125]
### Description of feature

Discovery tools can handle strandedness information to improve their result quality. Currently the pipeline offers no way of specifying the strandedness.

The following changes need to be made:

```[tasklist]
### Tasks
- [x] Update the samplesheet schema
- [x] Make sure the information gets passed through to the discovery tool
- [x] Find out which discovery tools can make use of the information
- [x] Add proper handling of the information in all tools supporting this
- [x] Update documentation
```

**Comment by nictru** [comment]
`ciriquant` has the `-l` parameter for this
