### ISSUE TITLE
Implement CIRI-full

### ISSUE THREAD

**Issue by nictru** [nf-core/circrna#134]
Documentation can be found [here](https://ciri-cookbook.readthedocs.io/en/latest/CIRI-full.html).

```[tasklist]
### Tasks
- [ ] Make sure outputs of `BWA` are available
- [ ] Implement CIRI
- [ ] Implement CIRI-AS
- [ ] Implement CIRI-full
```

**Comment by nictru** [comment]
Done via #211
