### ISSUE TITLE
Implement circRNAfull

### ISSUE THREAD

**Issue by nictru** [nf-core/circrna#135]
Documentation can be found [here](https://github.com/tofazzalh/circRNAFull)
The function [`extract_sequence`](https://github.com/tofazzalh/circRNAFull?tab=readme-ov-file#reconstruction-of-full-length-circrna-sequences) appears to be most relevant

```[tasklist]
### Tasks
- [ ] Make sure the necessary outputs from `STAR` are available
- [ ] Set up environment
- [ ] Implement `circRNAFull` process
```

**Comment by nictru** [comment]
Done via #211
