### ISSUE TITLE
Implement circRNA database annotation functionalities

### ISSUE THREAD

**Issue by nictru** [nf-core/circrna#138]
### Description of feature

Some candidates:

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/circrna/issues/139
- [ ] https://github.com/nf-core/circrna/issues/140
- [ ] https://github.com/nf-core/circrna/issues/141
- [ ] https://github.com/nf-core/circrna/issues/142
```

**Comment by nictru** [comment]
This can best be done by providing an additional input sample sheet with these columns:

- Identifier
- File (Bed File containing annotations)
- Minimal overlap (optional)
