### ISSUE TITLE
Decide how to proceed with the differential expression subworkflow

### ISSUE THREAD

**Issue by nictru** [nf-core/circrna#144]
### Description of feature

The way it is currently implemented is not state of the art. Especially the way the linear quantification is currently implemented is less than optimal. The results of the `QUANTIFICATION` subworkflow should be used here.

```[tasklist]
### Tasks
- [ ] Remove linear quantification in `DIFFERENTIAL_EXPRESSION`
- [ ] Replace DESeq2 with Fishpond/Swish
- [ ] Update `circtest` implementation
```
